// 用户信息
export const GET_USERINFO = 'GET_USERINFO'
export const RECORD_USERINFO = 'RECORD_USERINFO'
export const SET_HOMEPAGE = 'SET_HOMEPAGE'
export const SET_PLACELIST = 'SET_PLACELIST'
export const SET_REGIONLIST = 'SET_REGIONLIST'
